version: "3"
services:
  bydlac_backend:
    build: .
    volumes:
      - .:/backend
    ports: 
      - 8000:8000
    image: bydlac_backend:bydlac_backend
    container_name: bydlac_backend
    command: python /backend/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_IP=${DB_IP}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    networks:
      bydlac_network:
        ipv4_address: ${BACKEND_IP}
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: bydlac_postgres
    networks:
      bydlac_network:
        ipv4_address: ${DB_IP}
networks:
  bydlac_network:
    ipam: 
      driver: default
      config: 
        - subnet: ${BYDLAC_NETWORK_IP}
    

