# Generated by Django 4.1.3 on 2022-11-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_group_conversationgroup_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationgroup",
            name="update",
            field=models.DateTimeField(auto_now=True, verbose_name="last message time"),
        ),
    ]
