# Generated by Django 4.1.3 on 2022-11-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_update_conversationgroup_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="nickname", new_name="username",
        ),
    ]
