# Generated by Django 4.1.3 on 2022-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_nickname_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationgroup",
            name="is_private",
            field=models.BooleanField(default=True, verbose_name="is private"),
        ),
    ]
