# Generated by Django 4.1.3 on 2022-11-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_conversationgroup_is_private"),
    ]

    operations = [
        migrations.RenameModel(old_name="GroupParticipant", new_name="GroupMember",),
    ]
