# Generated by Django 4.1.3 on 2022-12-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_event_location_alter_event_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationgroup",
            name="is_event_group",
            field=models.BooleanField(default=False, verbose_name="is event group"),
        ),
        migrations.AlterField(
            model_name="event",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.conversationgroup",
            ),
        ),
    ]
