# Generated by Django 4.1.3 on 2022-12-25 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_conversationgroup_is_event_group_alter_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 22, 14, 24, 650202)),
        ),
    ]
