# Generated by Django 4.1.3 on 2023-01-02 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_event_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationgroup",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 2, 19, 23, 44, 882451, tzinfo=datetime.timezone.utc
                ),
                verbose_name="last message time",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 2, 19, 38, 44, 883749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
