# Generated by Django 4.1.3 on 2023-01-02 19:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_conversationgroup_updated_alter_event_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationgroup",
            name="updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last message time"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 2, 19, 40, 19, 178774, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
