# Generated by Django 4.1.3 on 2023-01-02 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_conversationgroup_updated_alter_event_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 2, 19, 40, 23, 652564, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
