# Generated by Django 4.1.3 on 2023-01-03 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_event_expires"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationgroup", options={"ordering": ["-last_message"]},
        ),
        migrations.RenameField(
            model_name="conversationgroup", old_name="updated", new_name="last_message",
        ),
        migrations.AlterField(
            model_name="event",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 3, 13, 35, 50, 457862, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
