# Generated by Django 4.1.3 on 2023-01-13 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_alter_event_expires_alter_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 13, 11, 59, 57, 139514, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
